language: cpp
dist: bionic
env:
- LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/lib/
script:
- cd lib && make clean && make
- cd .. && cd test
- rm test-main.o && rm unittest && g++ test-main.cpp -c
- g++ test-main.o test-init.cpp -o unittest -L ../lib/ -lBigInt && ./unittest
- g++ test-main.o test-add.cpp -o unittest -L ../lib/ -lBigInt && ./unittest
- g++ test-main.o test-sub.cpp -o unittest -L ../lib/ -lBigInt && ./unittest
- g++ test-main.o test-mul.cpp -o unittest -L ../lib/ -lBigInt && ./unittest
- g++ test-main.o test-div.cpp -o unittest -L ../lib/ -lBigInt && ./unittest
- g++ test-main.o test-others.cpp -o unittest -L ../lib/ -lBigInt && ./unittest